### ISSUE TITLE
Adapt integration for Kubernetes v1.22

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-kubernetes#158] opened 2021-07-16 07:30 UTC
In this version, multiple beta APIs will be *removed.* Not deprecated, removed. 
https://twitter.com/Dixie3Flatline/status/1415453193522139136?s=20

**Comment by invidian** [comment] 2021-08-10 11:21
I'll close as a duplicate of #186, even though it was created later.

**Closed by invidian** 2021-08-10 11:21 UTC
